const WORDPRESS_CATEGORY_ID_TO_CATEGORY = {
  7: "ALL",
  8: "INFORMATION",
  9: "NEWS",
  10: "TERMINOLOGY",
  11: "ADVISORY",
  12: "MANUAL",
}

const CATEGORY_TO_WORDPRESS_CATEGORY_ID = {
  "INFORMATION": 8,
  "NEWS": 9,
  "TERMINOLOGY": 10,
  "ADVISORY": 11,
  "MANUAL": 12,
}

export { WORDPRESS_CATEGORY_ID_TO_CATEGORY, CATEGORY_TO_WORDPRESS_CATEGORY_ID }