const WORDPRESS_CATEGORY_ID_TO_CATEGORY = {
  3: "INFORMATION",
  2: "NEWS",
  4: "TERMINOLOGY",
  5: "ADVISORY",
  6: "MANUAL",
}

const CATEGORY_TO_WORDPRESS_CATEGORY_ID = {
  "INFORMATION": 3,
  "NEWS": 2,
  "TERMINOLOGY": 4,
  "ADVISORY": 5,
  "MANUAL": 6,
}

export { WORDPRESS_CATEGORY_ID_TO_CATEGORY, CATEGORY_TO_WORDPRESS_CATEGORY_ID }